eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:codedecode@atlas-cluster.dnv3q1w.mongodb.net/?retryWrites=true&w=majority # mongodb://localhost:27017/orderdb
      host: atlas-cluster.dnv3q1w.mongodb.net
      port: 27017
      database: orderdb
      repositories:
        enabled: false